💚Fix indentation destroy Workflow

diff --git a/.github/workflows/destroy.yaml b/.github/workflows/destroy.yaml
--- a/.github/workflows/destroy.yaml
+++ b/.github/workflows/destroy.yaml
@@ -27,10 +27,10 @@ jobs:
 
     steps:
       - name: Confirm Uphold
-        if: inputs.uphold == false
-          run: |
-            echo "🚫 Destruction aborted. You must confirm by setting uphold: true"
-            exit 1
+        if: ${{ inputs.uphold == false }}
+        run: |
+          echo "🚫 Destruction aborted. You must confirm by setting uphold: true"
+          exit 1
 
       - name: Setup Environment variable
         run: |
